ARG ELIXIR_VERSION=1.14.0
ARG OTP_VERSION=24.0.5
ARG DEBIAN_VERSION=bullseye-20210902-slim

ARG BUILDER_IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"
ARG RUNNER_IMAGE="debian:${DEBIAN_VERSION}"

FROM ${BUILDER_IMAGE} as builder

# install build dependencies
RUN apt-get update -y && apt-get install -y build-essential git inotify-tools

# prepare build dir
WORKDIR /app

# install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# install mix dependencies
COPY mix.exs mix.lock ./
RUN mix deps.get --only $MIX_ENV

# Copy the rest of the application code to the container
COPY . .

# Expose the necessary ports (change these if needed)
EXPOSE 4000

# Set the environment variable for running in development mode
ENV MIX_ENV=dev

# Start the Elixir application
CMD ["mix", "phx.server", "--no-halt"]
